spring:
  datasource:
    url: jdbc:h2:mem:moim
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true